// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3x7rN_VjAm7B_gZE_DtqHo2y2jZlpxPU',
    appId: '1:758551703230:web:1b9503d410dd3104b0f8ef',
    messagingSenderId: '758551703230',
    projectId: 'smart-624cb',
    authDomain: 'smart-624cb.firebaseapp.com',
    storageBucket: 'smart-624cb.appspot.com',
    databaseURL: 'https://smart-624cb-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBMbqeMxCE2iXtUs-d5e8C9CupEl0cBA',
    appId: '1:758551703230:android:cb35af1127cb672cb0f8ef',
    messagingSenderId: '758551703230',
    projectId: 'smart-624cb',
    storageBucket: 'smart-624cb.appspot.com',
    databaseURL: 'https://smart-624cb-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6zpVSWjVFBhIxa8opLOeZV1YmxkoWc4w',
    appId: '1:758551703230:ios:51553af6f09dfb66b0f8ef',
    messagingSenderId: '758551703230',
    projectId: 'smart-624cb',
    storageBucket: 'smart-624cb.appspot.com',
    iosBundleId: 'com.example.smartfarm',
    databaseURL: 'https://smart-624cb-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6zpVSWjVFBhIxa8opLOeZV1YmxkoWc4w',
    appId: '1:758551703230:ios:51553af6f09dfb66b0f8ef',
    messagingSenderId: '758551703230',
    projectId: 'smart-624cb',
    storageBucket: 'smart-624cb.appspot.com',
    iosBundleId: 'com.example.smartfarm',
    databaseURL: 'https://smart-624cb-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3x7rN_VjAm7B_gZE_DtqHo2y2jZlpxPU',
    appId: '1:758551703230:web:bff816f30041d50ab0f8ef',
    messagingSenderId: '758551703230',
    projectId: 'smart-624cb',
    authDomain: 'smart-624cb.firebaseapp.com',
    storageBucket: 'smart-624cb.appspot.com',
    databaseURL: 'https://smart-624cb-default-rtdb.firebaseio.com/',
  );
}
